# catalog-info.yaml

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    # A anotação abaixo é vital para o Backstage encontrar o repositório no GitHub.
    # Certifique-se de substituir 'seu-usuario' pelo seu nome de usuário.
    github.com/project-slug: LuizRojas/${{ values.name }}
spec:
  type: service
  owner: ${{ values.owner }}
  lifecycle: experimental
