apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-tech-doc
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: produtos-internos
